### PR TITLE
Add `Seam::ClientMultiWorkspace`

### PR DESCRIPTION
**Pull request by andrii-balitskyi**
- **Add Seam::ClientMultiWorkspace**
- **Test**

### CODE REVIEW

**Comment by andrii-balitskyi** [comment]
`**` syntax seems to be invalid for ruby 3.1. @razor-x, do we want to continue supporting version 3.1? 
image

**Comment by razor-x** [comment]
I don't think we should drop support for 3.1 over this one case. Any alternative? Maybe we just need to manually maintain the parameters for now and add a todo / issue to use this syntax when we eventually drop support for 3.1 EOL on 2025-03-31

**Comment by andrii-balitskyi** [comment]
@razor-x the formatter was rewriting `**kwargs` to `**` making the code incompatible with 3.1. I moved the proxy class into a separate file and disabled formatter for that file. Does that look good? https://github.com/seamapi/ruby-next/pull/56/commits/43c6b75ed9b0b21ed5d0d8a6f1e4da414b3c40a1

**Review by razor-x — APPROVED** [review]
Nice!

**Pull request merged**
